config/routes.rb
SiliconVesion::Application.routes.draw do

  root :to => "home#index"

  scope "(:locale)", locale: /en|ch|ja/ do
    get '/' => "home#index"
    get "news/index"

    match "/newsletters/subscribe" => "newsletters#subscribe"
    match "aj/datasheets/request"  => "dataConverter#request_datasheet" , :method => "POST"

    get '/demos/order' => 'main_products#order_demo'
    post '/demos/order' => 'main_products#create_order'

    match ':action' => 'home#:action'
    match '/sivi-media/:media_name' => 'news#index'
    # match 'ips/:controller/:action' => ':controller#:action'

    match ':controller/:action' => ':controller#:action'
  end
end

app/models/order.rb
class Order
  extend  ActiveModel::Naming
  extend  ActiveModel::Translation
  include ActiveModel::Validations
  include ActiveModel::Conversion

  def initialize(attributes={})
    if attributes
      attributes.each do |name, value|
        send("#{name}=", value)
      end
    end
  end

  attr_accessor :name, :title, :email, :company, :website, :tel, :boards_number, :process_node, :address


  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	define_method('communication-systems') do
  	end

  	define_method('tire-pressure-monitoring') do
  	end

  	define_method('advanced-remote-controls') do
  	end

  	define_method('sensor-networks') do
  	end

  	define_method('wirless-health-monitors') do
  	end

  	define_method('wirless-industrial-control') do
  	end

  	define_method('remote-control-toys') do
  	end

  	define_method('home-automation-security-n-alarm') do
  	end

  	define_method('wireless-pc-peripherals') do
  	end

  	define_method('smart-meters') do
  	end

    before_filter :set_locale
    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

    def default_url_options(options={})
      { locale: I18n.locale }
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def applications
  end

  define_method('sivi-media') do
  end

  define_method('press') do
  end

  def careers
  end

  def contact
    if request.post?
      Rails.logger.debug {"User #{params["user"]["name"]} is sending a message"}
      user = params["user"]
      msg = params["message"]
      begin
        ContactMailer.email_message(user, msg).deliver
        flash.now[:notice] = "Message Sent"
        Rails.logger.info {"User #{params["user"]["name"]} sent a message"}
      rescue
        flash.now[:error] = "Problem with sending the message"
        Rails.logger.error {"User #{params["user"]["name"]} encountered a problem when sending a message"}
      end
    end
  end

end

app/controllers/ips_controller.rb
class IpsController < ApplicationController

  define_method('index') do
  end

  define_method('bluetooth-low-energy') do
  end

  define_method('sub-1ghz') do
  end

  define_method('zwave') do
  end

  define_method('zigbee') do
  end

end

app/controllers/main_products_controller.rb
class MainProductsController < ApplicationController

  layout 'main_products_layout'

  def index
  end

  def bluetooth_low_energy
  end

  def order_demo
    @order= Order.new
  end

  def create_order
    @order = Order.new(params[:order])

    begin
      OrderMailer.order_email(@order).deliver
      flash[:notice] = "Message Sent!"
      Rails.logger.info {"User #{params["order"]["name"]} sent a message"}
      redirect_to(demos_order_path)
    rescue Exception => e
      flash.now[:error] = "Problem with sending the message"
      Rails.logger.error {"User #{params["order"]["name"]} encountered a problem (#{e}) when sending a message"}
      render :action => 'order_demo'
    end
  end

  def updates
  end

  def partners
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  	render template: 'news_latest/'+params[:media_name]
  end
end

app/controllers/news_list_controller.rb
class PowerManagementController < ApplicationController
  define_method('index') do
  end
  
  define_method('band-gap-reference') do
  end
  
  define_method('dc-dc-buck-converters') do
  end

  define_method('temperature-sensors') do
  end

  define_method('por-supply-monitors') do
  end

  define_method('linear-chargers') do
  end

  define_method('loe-drop-out-regulators') do
  end
end

app/controllers/newsletters_controller.rb
require "mailchimp"

class NewslettersController < ApplicationController
  def subscribe
    begin
      mailchimp = Mailchimp::API.new(Rails.application.config.mail_chimp_api_key)
      subscriber = params[:user][:address]
      Rails.logger.debug {"subscription to newsletter has been requested by email #{subscriber}"}
      list_id = mailchimp.lists["data"].first["id"]
      Rails.logger.debug {"subscribing to mailing list #{list_id}"}
      resp = mailchimp.listSubscribe(id: list_id, email_address: subscriber, email_type: 'html')
      @suceed_message = t(:successful_subscription)
      @error = nil
      Rails.logger.info {"A confirmation to newsletter subscription has been sent to address #{subscriber}"}
    rescue Mailchimp::APIError => e
      @suceed_message = nil
      if e.message.start_with? "<502>"
        Rails.logger.error {"#{subscriber} is an invalid email address"}
        @error = t(:invalid_address)

      elsif e.message.start_with? "<214>"
        Rails.logger.error {"User #{subscriber} is already subscribed"}
        @error = t(:already_registered)

      end
    rescue Exception => e
        Rails.logger.error {"Subscription failed for user #{subscriber}"}
        @error = t(:failed_subscription) 
    end
  
    respond_to do |format|
    format.html {render "static/contact"}
    format.json {render :json=>{:success=>@suceed_message, :error=>@error} }
    end
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  def get_localized_path(lang)
    current_path = request.fullpath

    ["en", "ch", "ja"].each do |g|
      current_path.gsub! "/#{g}", ""
    end

    if current_path == "/" || current_path.blank?
      "/#{lang}"
    else
      "/#{lang}#{current_path}"
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/main_products_helper.rb
module MainProductsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/ams/clockgenerators-synthesizer.html.erb
clockgenerators-synthesizer

app/views/ams/realtimecLocks-oscillators.html.erb
realtimecLocks-oscillators

app/views/application/advanced-remote-controls.html.erb
advanced-remote-controls

app/views/application/communication-systems.html.erb
<% content_for :title do %>
  Communication Systems
<% end %>

<div class="head-strip">
	<div class="container">
		<h4 class="pull-left">
			<strong>Silicon Vision's</strong> Story			
		</h4>
		<div  class="pull-right fszs">
			<%= link_to('HOME', {:controller => 'home', :action => 'index'}) %>
			<span>/ About us</span>
		</div>
	</div>
</div>
<!-- head strip end -->
<div id="app-page-template" class="container">
	<div class="row">
		<div class="col-lg-8">
			<h2></h2>
		</div>
	</div>
</div>

app/views/application/home-automation-security-n-alarm.html.erb
home-automation-security-n-alarm

app/views/application/remote-control-toys.html.erb
remote-control-toys

app/views/application/sensor-networks.html.erb
sensor-networks

app/views/application/smart-meters.html.erb
smart-meters

app/views/application/tire-pressure-monitoring.html.erb
tire-pressure-monitoring

app/views/application/wireless-pc-peripherals.html.erb
wireless-pc-peripherals

app/views/application/wirless-health-monitors.html.erb
wirless-health-monitors

app/views/application/wirless-industrial-control.html.erb
wirless-industrial-control

app/views/home/about.html.erb
<% content_for :title do %>
  <%= t :about %>
<% end %>

<% content_for :description do %>
  <%= t :si_vi_intro_2 %>
<% end %>

<% content_for :keywords do %>
  Silicon Vision,IP,provider,high-performance,low power,radio,frequency,intellectual property,RFIP,solutions,Bluetooth,low energy,technology,low power,Zigbee like,RF,advanced power management
<% end %>

<div class="head-strip">
	<div class="container">
		<h4 class="pull-left">
      <%= t :about_us_si_vi_story %>
		</h4>
		<div  class="pull-right fszs">
			<%= link_to(t(:home), {:controller => 'home', :action => 'index'}) %>
			<span>/ <%= t :about %></span>
		</div>
	</div>
</div>
<!-- head strip end -->
<div id="about-page" class="container">
	<div class="row">
		<div class="col-lg-8">
      <h3><%= t :about_us_welcome %></h3>
			<p>
      			<%= t :about_us_parag_1 %>
 			<p>
      			<%= t :about_us_parag_2_1 %> <a href="http://news.synopsys.com/2015-07-16-Synopsys-Acquires-Bluetooth-Smart-IP-from-Silicon-Vision"><%= t :about_us_parag_2_2 %></a>
			</p>
			<p>	 
     			<%= t :about_us_parag_3 %>
			</p>
		</div>
		<div class="col-lg-4 visible-lg center-txt">
			<img src="/assets/office-sivi.png" />
		</div>
	</div>
</div>

app/views/home/applications.html.erb
<% content_for :title do %>
  <%= t :apps %>
<% end %>

<% content_for :description do %>
  <%= t :ips_desc %>
<% end %>

<% content_for :keywords do %>
  Silicon Vision,offers,high performance,IP,Radio frequency,RF,Power Management,PM,data-converters,DC,AMS,silicon proven,data converters
<% end %>

<div class="head-strip">
	<div class="container">
		<h4 class="pull-left">
      <%= t :apps_title %>
		</h4>
		<div  class="pull-right fszs">
			<%= link_to(t(:home), {:controller => 'home', :action => 'index'}) %>
      <span>/ <%= t :apps %></span>
		</div>
	</div>
</div>
<!-- head strip end -->
<div id="apps-page" class="container">
	<div class="row">
      <!-- IOT -->
      <div class="col-lg-3 pull-left">
        <a class="app-caption" data-toggle="modal" href="#tot">
          <img class="img-thumbnail" width="260px" height="250" src="/assets/tot.jpg">
          <span class="caption">
            <p><%= t :app_tot_0 %></p>
          </span>
        </a>
       <div class="modal fade" id="tot">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title"><%= t :app_tot_0 %></h4>
            </div>
            <div class="modal-body">
              <p>
                  <%= t :app_tot_1 %>
              </p>
              <%= link_to(t(:app_wireless_monitors_2), {
                      :controller => 'ips',
                      :action => 'bluetooth-low-energy'
                  }) %>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    </div>

    <!-- Home Automation -->
    <div class="col-lg-3 pull-left">
      <a class="app-caption" data-toggle="modal" href="#home-auto">
        <img class="img-thumbnail" src="/assets/home-automation.png">
        <span class="caption">
          <p><%= t :app_hw_0 %></p>
        </span>
      </a>
    <div class="modal fade" id="home-auto">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title"><%= t :app_hw_0 %></h4>
            </div>
            <div class="modal-body">
              <p>
                  <%= t :app_hw_1 %>
              </p>
              <%= link_to(t(:app_hw_3), {
              :controller => 'ips',
              :action => 'bluetooth-low-energy'
              }) %>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    </div>

    <!-- wearable tech -->
    <div class="col-lg-3 pull-left">
        <a class="app-caption" data-toggle="modal" href="#toys">
          <img class="img-thumbnail" style="width:260px;height:250px" src="/assets/wearabletech.jpg">
          <span class="caption">
            <p><%= t :app_wt_0 %></p>
          </span>
        </a>
        <div class="modal fade" id="toys">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><%= t :app_wt_0 %></h4>
              </div>
              <div class="modal-body">
                <p>
        <%= t :app_wt_1 %>
                </p>
                <%= link_to(t(:app_wt_2), {
                        :controller => 'ips',
                        :action => 'bluetooth-low-energy'
                    }) %>
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
    </div>

    <!-- Smart Meter -->
    <div class="col-lg-3 pull-left">
      <a class="app-caption" data-toggle="modal" href="#smart-meter">
        <img class="img-thumbnail" src="/assets/smart-meter.png">
        <span class="caption">
          <p><%= t :app_wireless_meters_0 %></p>
        </span>
      </a>
      <div class="modal fade" id="smart-meter">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title"><%= t :app_wireless_meters_0 %></h4>
            </div>
            <div class="modal-body">
              <p>
                  <%= t :app_wireless_meters_1 %>
              </p>
              <%= link_to(t(:app_wireless_meters_2),{:controller => 'ips', :action => 'sub-1ghz'}) %>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    </div>

    <!-- Wireless Health -->
    <div class="col-lg-3 pull-left">
        <a class="app-caption" data-toggle="modal" href="#health">
          <img class="img-thumbnail" src="/assets/wirelesshealth-monitor.png">
          <span class="caption">
            <p><%= t :app_wireless_monitors_0 %></p>
          </span>
        </a>

        <div class="modal fade" id="health">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><%= t :app_wireless_monitors_0 %></h4>
              </div>
              <div class="modal-body">
                <p>
                    <%= t :app_wireless_monitors_1 %>
                </p>
                <%= link_to(t(:app_wireless_monitors_2), {
                        :controller => 'ips',
                        :action => 'bluetooth-low-energy'
                    }) %>
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
    </div>



    <div class="col-lg-3 pull-left">
    <a class="app-caption" data-toggle="modal" href="#com-sys">
      <img class="img-thumbnail" src="/assets/comunication-system.png">
      <span class="caption">
        <p><%= t :app_comm_0 %></p>
      </span>
    </a>
    <div class="modal fade" id="com-sys">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title"><%= t :app_comm_0 %></h4>
          </div>
          <div class="modal-body">
            <p><%= t :app_comm_1 %></p>
            <%= link_to(t(:app_comm_2), {:controller => 'ips', :action => 'sub-1ghz'}) %>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    </div>

    <div class="col-lg-3 pull-left">
    <a class="app-caption" data-toggle="modal" href="#wireless-ind">
    <img class="img-thumbnail" src="/assets/2.png">
    <span class="caption">
      <p><%= t :app_industrial_ctrl_0 %></p>
    </span>
    </a>

    <div class="modal fade" id="wireless-ind">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title"><%= t :app_industrial_ctrl_0 %></h4>
        </div>
        <div class="modal-body">
          <p>
            <%= t :app_industrial_ctrl_1 %>
          </p>
          <%= link_to(t(:app_industrial_ctrl_2), {:controller => 'ips', :action => 'sub-1ghz'}) %>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    </div>



    <div class="col-lg-3 pull-left">
    <a class="app-caption" data-toggle="modal" href="#remote-control">
      <img class="img-thumbnail" src="/assets/4.png">
      <span class="caption">
        <p><%= t :app_remote_controls_0 %></p>
      </span>
    </a>
    <div class="modal fade" id="remote-control">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title"><%= t :app_remote_controls_0 %></h4>
          </div>
          <div class="modal-body">
            <p>
    <%= t :app_remote_controls_1 %>
            </p>
            <%= link_to(t(:app_remote_controls_2), {
                    :controller => 'ips',
                    :action => 'bluetooth-low-energy'
                }) %>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    </div>




      <div class="col-lg-3 pull-left">
      <a class="app-caption" data-toggle="modal" href="#tire-pres">
        <img class="img-thumbnail" src="/assets/Tire-pressure-monitoring.png">
        <span class="caption">
          <p><%= t :app_tire_pressure_0 %></p>
        </span>
      </a>
      <div class="modal fade" id="tire-pres">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title"><%= t :app_tire_pressure_0 %></h4>
            </div>
            <div class="modal-body">
            <p>
      <%= t :app_tire_pressure_1 %>
            </p>
              <%= link_to(t(:app_tire_pressure_2), {:controller => 'ips', :action => 'sub-1ghz'}) %>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
      </div>

      <div class="col-lg-3 pull-left">
      <a class="app-caption" data-toggle="modal" href="#sensor-net">
        <img class="img-thumbnail" src="/assets/sensor-networks.png">
        <span class="caption">
          <p><%= t :app_sensor_networks_0 %></p>
        </span>
      </a>

       <div class="modal fade" id="sensor-net">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title"><%= t :app_sensor_networks_0 %></h4>
            </div>
            <div class="modal-body">
              <p>
      <%= t :app_sensor_networks_1 %>
              </p>
              <%= link_to(t(:app_sensor_networks_2), {:controller => 'ips', :action => 'sub-1ghz'}) %>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
      </div>



      <div class="col-lg-3 pull-left">
      <a class="app-caption" data-toggle="modal" href="#wt">
       <img class="img-thumbnail" src="/assets/remote-control-toys.png">

        <span class="caption">
          <p><%= t :app_rc_toys_0 %></p>
        </span>
      </a>
         <div class="modal fade" id="wt">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title"><%= t :app_rc_toys_0 %></h4>
            </div>
            <div class="modal-body">
              <p>
      <%= t :app_rc_toys_1 %>
              </p>
              <%= link_to(t(:app_wt_2), {
                      :controller => 'ips',
                      :action => 'bluetooth-low-energy'
                  }) %>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
      </div>




      <div class="col-lg-3 pull-left">
      <a class="app-caption" data-toggle="modal" href="#wireless-pc">
        <img class="img-thumbnail" src="/assets/wireless-pc-peripherals.png">
        <span class="caption">
          <p><%= t :app_wireless_periphs_0 %></p>
        </span>
      </a>
      <div class="modal fade" id="wireless-pc">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title"><%= t :app_wireless_periphs_0 %></h4>
            </div>
            <div class="modal-body">
              <p>
      <%= t :app_wireless_periphs_1 %>
              </p>
              <%= link_to(t(:app_wireless_periphs_2), {
                      :controller => 'ips',
                      :action => 'bluetooth-low-energy'
                  }) %>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
      </div>







</div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<% content_for :head do %>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<% end %>

<%= render "snippets/head" %>

<body class="<%= controller_name %> <%= action_name %>">
  <%= render :partial => "layouts/snippets/flash_msg" %>
  <%= render "snippets/mainheader" %>
  <%= yield %>
  <div id="footer">
    <%= render "snippets/footer" %>
  </div>
  <%= javascript_include_tag "countries2" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.scrollTo-min" %>
  <%= yield(:javascript) %>

  <script type="text/javascript" charset="utf-8">
    function announceMessage(message, level) {
      resetBox(function() {
        $("#general-box").removeClass('hidden');
        $("#general-box").addClass(level);
        $("#general-box p").text(message);
        $("#general-box").slideDown("normal");
        $.scrollTo("#general-box", 500, {offset:{top:-100}});
      });
    }
    function announceError(message)  { announceMessage(message, 'error')  }
    function announceWarn(message)   { announceMessage(message, 'warn')   }
    function announceNotice(message) { announceMessage(message, 'notice') }
    function announceInfo(message)   { announceMessage(message, 'notice') }
    function resetBox(callback) {
      var element = $("#general-box");
      if (element.is(":visible")) {
        element.slideUp("normal", function() {
          element.removeClass('warn').removeClass('notice').removeClass('error');
          if (callback) {
            callback();
            return;
          }
        });
      }
      if (callback) {
        callback();
      }
    }

    $(function() {
      $('#subscribe-form').submit(function(e) {
        e.preventDefault();
        $.ajax({
          beforeSend: function () {
            $('#subscribe-btn').attr('disabled', 'disabled');
          },
          url: '<%= newsletters_subscribe_path(:format => 'json') %>',
          data: $('#subscribe-form').serialize(),
          success: function(data) {
            if(data.error) {
              announceError(data.error);
            } else if(data.success) {
              announceInfo(data.success);
            }
            $('#subscribe').val('');
            $('#subscribe-btn').removeAttr('disabled');
          },
          error: function(data) {
            announceError('Some error occured while processing your request. Please try again in a few minutes.');
            $('#subscribe').val('');
            $('#subscribe-btn').removeAttr('disabled');
          }
        });
      });
    });

    $(document).on("click", ".data-req-btn", function () {
      var requestId = $(this).data('id');
      $(".modal-body #product").val( requestId );
    });
    $('#data-req form').on("submit", function(e) {
      e.preventDefault();
      console.log($(this).serialize())  ;
      $.ajax({
        type: "POST",
        url: "/aj/datasheets/request",
        data: $(this).serialize()
      }).done(function(res) {$('.modal').modal("hide");announceInfo(res["msg"]) ;})
      .fail(function() { $('.modal').modal("hide");announceError(res["msg"]) ;});
    });
  </script>

  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-3480657-2']);
    _gaq.push(['_setDomainName', 'si-vision.com']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</body>
</html>

app/views/main_products/index.html.erb
<h4 class="title">Index</h4>

app/views/power_management/ldos.html.erb
LDOs

app/views/snippets/_footer.html.erb
  <div class="container">
    <div class="row">
      <h3 class="col-lg-6 col-lg-offset-3"><%= t :subscribe %> </h3>
      <%= form_tag(newsletters_subscribe_path(:format => 'json'), :id=>'subscribe-form', :class=>'input-group col-lg-6 col-lg-offset-3') do %>
      <div style="margin-left:0;">
        <%= email_field(:user, :address, :required => true, :placeholder => t(:write_email), :id =>"subscribe", :class => "form-control")%>
      </div>
      <span class="input-group-btn">
        <%= submit_tag(t(:go), :id=> 'subscribe-btn', :class => 'btn btn-primary')%>
      </span>
      <% end %>
    </div>
  </div>

  <div id="copyrights">
    <div class="container">
      <div class="row">
        <p class="col-lg-11 pull-left"><%= t(:copyright) %></p>
        <ul class="col-lg-1 pull-right nav nav-pills" id="social-links">
          <li>
            <a target="_blank" href="https://www.facebook.com/pages/Si-Vision/491451230062">
              <img src="/assets/facebook-icon2x.png" width="20px" height="20px">
            </a>
          </li>
          <li>
            <a target="_blank" href="https://twitter.com/Si_Vision">
              <img src="/assets/twitter-icon2x.png" width="20px" height="20px">
            </a>
          </li>
          <li>
            <a target="_blank" href="http://www.linkedin.com/company/209215?trk=tyah">
              <img src="/assets/linkedin-icon2x.png" width="20px" height="20px">
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>